### ISSUE TITLE
feat: boot all development servers with SSL by default

### ISSUE THREAD

**Issue by EmirBoyaci** [kamp-us/pano#685]
### Describe the feature you would like to see added

As @emredevsalot mentioned [here](https://github.com/kamp-us/monorepo/pull/668#discussion_r1299177155) Twitch does **only** support secure (HTTPS) urls. To use Twitch auth strategy in Pasaport, we need to run Pasaport via SSL. Then, @usirin draw forth an idea to boot all development servers with SSL by default.

We can do that via [local-ssl-proxy](https://www.npmjs.com/package/local-ssl-proxy) which grabs the source port and publishes new port with SSL. See example usage below:

```sh
# install concurrently to run multiple commands concurrently
npm install -g concurrently

# run 'npm run dev' and 'npx local-ssl-proxy --target 3000 --source 3001' concurrently
# you can change 'target' and 'source' parameters
# since target port '3000' is default port for Next.js server I keep this and make source as '+1'
concurrently "npm run dev" "npx local-ssl-proxy --target 3000 --source 3001"
```

If we do what I described above, we will able to access HTTP on port 3000 and HTTPS on port 3001 for example which makes things easier.

**BREAKING CHANGE**: If we are not writing cookies via `secure` property, we might get some troubles via accessing cookies from HTTPS websites? (might be the case, just FYI)

See output below:
![output of 'concurrently "npm run dev" "npx local-ssl-proxy --target 3000 --source 3001"'](https://github.com/kamp-us/monorepo/assets/59085992/08d6dafe-7eb1-42c7-8c30-e6373183d42d)

cc/ @emredevsalot @usirin @gurkanguray

**Comment by emredevsalot** [comment]
I got an error with the `3001` port, I guess it was because it conflicts with `pasaport` trying to run on the same port.

I changed the source as `--source 8001` and ran the command. The app works as expected without SSL URLs, but when I try to access with `https`, I get the following error.

![image](https://github.com/kamp-us/monorepo/assets/72770244/b0754af5-9813-4139-b965-7a0302106526)

Has anyone else tried this? Maybe it's on my end.

**Comment by EmirBoyaci** [comment]
> I got an error with the `3001` port, I guess it was because it conflicts with `pasaport` trying to run on the same port.
> 
> I changed the source as `--source 8001` and ran the command. The app works as expected without SSL URLs, but when I try to access with `https`, I get the following error.
> 
> ![image](https://user-images.githubusercontent.com/72770244/262016378-b0754af5-9813-4139-b965-7a0302106526.png)
> 
> Has anyone else tried this? Maybe it's on my end.

I just tried and it works, maybe it's because you're running on Windows? IDK why it's like that but could you please try in the terminal?

```sh
# go to pasaport directory (full path: monorepo/apps/pasaport)
cd /monorepo/apps/pasaport

# install concurrently to run multiple commands concurrently
npm install -g concurrently

# run 'npm run dev' and 'npx local-ssl-proxy --target 3001 --source 9001' concurrently
# ! THIS ENSURES THAT PORT '9001' IS AVAILABLE !
concurrently "npm run dev" "npx local-ssl-proxy --target 3001 --source 9001"

# if you do not have wget you can install
winget install -e --id JernejSimoncic.Wget

# try to fetch HTTP
wget http://pasaport.localhost.kamp.us:3001/

# try to fetch HTTPS
wget https://pasaport.localhost.kamp.us:9001/ --no-check-certificate
```

See example output:
![image](https://github.com/kamp-us/monorepo/assets/59085992/a6881f4b-ce35-471c-aae2-c380c92bb29e)

If your output is different than mine, something doesn't work on Windows. If you can share your output we can look together.

P.S. getting 404 error is fine since there is no Next.js entrypoint on root path (/)
